version: '3.7'

services:
  test-image:
    container_name: test_image
    build:
      context: .
      dockerfile: Dockerfile
    command: [sh, -cx, "yarn install ; yarn run start"]
    ports:
      - '4200:4200'
    volumes:
      - ./:/app
