version: '3.7'

services:
  example:
    image: node:12-alpine3.14
    command: [sh, -cx, "yarn install ; yarn run start"]
    ports:
      - '4200:4200'
    working_dir: /app
    volumes:
      - ./:/app
